### ISSUE TITLE
Calculate a lot of features for the sample dataset

### ISSUE THREAD

**Issue by JJanowiak** [IBM/pychemex#5]
which features to be decided. will need to look at MP prediction papers and what's freely and easily available.
Try grouping the features into categories based on what they intend to capture, so specific features could be "turned off" to show the functionality of the library.

Will probably split this into multiple issues later.

**Comment by Alex-AMC** [comment]
Suggested categories for features: 

- 2D/3D
- Chemical / Spatial 
- Intermolecular / Intramolecular
- Molecular Data/ Crystal Data

**Comment by JJanowiak** [comment]
2 csvs
1. features calculations
SMILES per row, feature per column

2. feature category
feature per row, category per column

**Comment by JJanowiak** [comment]
Contains a very poor image of potential categories:
http://datascience.unm.edu/biomed505/Course/Cheminformatics/basic/descs_fingers/molec_descs_fingerprints.htm

categories are:
- Constitutional: derived from atomic composition (e.g. mol weight, how many rings )
- Topological: derived from molecular graph (Random walks etc)
- Geometric: 3D descriptors (mol volume)
- Electrostatic: derived from partial charges
- Quantum-Chemical: derived from molecular electron wave function (thermodynamic properties, orbital energies)

**Comment by JJanowiak** [comment]
https://www.rdkit.org/docs/source/rdkit.Chem.QED.html
https://www.rdkit.org/docs/source/rdkit.Chem.rdMolDescriptors.html
https://www.rdkit.org/docs/source/rdkit.Chem.Lipinski.html

**Comment by Alex-AMC** [comment]
We could use [CDK](https://cdk.github.io/) and a [python wrapper](https://github.com/sebotic/cdk_pywrapper)  To calculate a set of descriptors

**Comment by Alex-AMC** [comment]
[SCINE  - Molassembler](https://scine.ethz.ch/download/molassembler) has the ability to do molecular graphs and a bunch of other descriptors. Written in C++ but has a python key bindings available?

**Comment by Alex-AMC** [comment]
Descriptors to be saved as .CSV

**Comment by Alex-AMC** [comment]
Calculated descriptors using built in class for calculating all descriptors : 
[rdkit.ML.Descriptors](https://www.rdkit.org/docs/source/rdkit.ML.Descriptors.Descriptors.html#rdkit.ML.Descriptors.Descriptors.DescriptorCalculator)

Left computer over night to calculate 208 descriptors for 274,978 SMILEs.
